# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Treexy.DriverFusion
PackageVersion: 12.1.0.1
InstallerType: exe
InstallerSwitches:
  Silent: /qn
  SilentWithProgress: /qb
  Custom: /norestart
UpgradeBehavior: install
ProductCode: '{213424AB-820F-4E06-8D18-BFC966EF2A66}'
Installers:
- Architecture: neutral
  InstallerUrl: https://treexy.com/media/tp2deohg/driverfusionfreesetup.exe
  InstallerSha256: 47757B4146F724C52DE8F2D5D15DEF336499855AA0A0AFD50FF3D12E935E6B6A
ManifestType: installer
ManifestVersion: 1.9.0
